#+title: Lucid Framework(Εργασία 1)

* Task 1: Create a High Concept Statement for the product

RecycleRanger is a waste reduction and sustainability app for kids. It tracks waste and provides insights to educate and engage children in protecting the environment.

* Task 2: Identify the business objectives the product wil serve

RecycleRanger app is a game designed to increase the environmental sensitivity of the elementary school student’s, especially on recycling. Our goal is to motivate them to change their everyday habits based on a small competition, in order to make them responsible civilians.

* Task 3: Identify the user population

| User                          | Age Range |
|-------------------------------+-----------|
| kidergarten students          | 5         |
| early primary school students | 6 - 9     |
|-------------------------------+-----------|

Also the teachers of those classes

* Task 4: Identify usability goals

For student's using the app:

- The ui will need to be friendly for kids to use and also be stimulating in order not to be boring to them.

- It will need to capture their intrest and provide some type of reward to encourage them keep playing the game.

For the teacher's using the app:

- The ui should not be confusing in order for them to manage the whole process smoothly(needs to be really intuitive).

- Have administrative access over the class through the app

* Task 5: Identify high-level constrains

* Task 6: Identify high-level functionality

* Task 7: Produce screen sketches

* Task 8: Create the project plan

* Task 9: Create the UI Roadmap
