from typing import Any, Union, Callable, TypeVar

from fastapi import APIRouter, Depends, HTTPException, status
from fastapi.security import OAuth2PasswordRequestForm
from sqlalchemy.orm.session import Session

from app.api import deps
from app.crud import student
from app.models.teacher import Teacher
from app.models.student import Student
from app import schemas
from app.core.myTypes import UsrType, CurrentUsr


router = APIRouter()

User = TypeVar("User", Teacher, Student)

@router.get("/{teacher_id}")
def get_class(
        teacher_id: int,
        skip: int = 0,
        limit: int = 100,
        db: Session = Depends(deps.get_db),
        current_user: CurrentUsr = Depends(deps.get_user)
) -> Any:
    """
    Get all the Students of a class
    """
    credential_error: Callable[[str], Any] = lambda msg: HTTPException(
        status_code=status.HTTP_401_UNAUTHORIZED,
        detail=msg,
    )

    if current_user.type == UsrType.teacher:
        teacher_usr: Teacher = current_user.user
        if teacher_usr.id == teacher_id:
            return student.get_class(
                db=db,
                class_id=teacher_id,
                skip=skip,
                limit=limit,
            )
        else:
            raise credential_error("You are trying to access a class that doesn't belong to you.")

    elif current_user.type == UsrType.student:
        student_usr: Student = current_user.user
        class_id: int = int(student_usr.class_id) # type: ignore
        if class_id == teacher_id:
            return student.get_class_cens(
                db=db,
                class_id=teacher_id,
                skip=skip,
                limit=limit,
            )
        else:
            raise credential_error("You are trying to access a class you are not a member of.")
    raise credential_error("You don't have access to this information. Please log in.")

@router.post("/{teacher_id}/autogenerate/{num}")
def post_autogenerate_class(
        teacher_id: int,
        num: int,
        skip: int = 0,
        limit: int = 100,
        db: Session = Depends(deps.get_db),
        current_user: CurrentUsr = Depends(deps.get_user),
) -> Any:
    """
    Create a `num` of Students with autogenerated password and returns the passwords
    """
    pass
