"""Minor change

Revision ID: 7842b8dc7f08
Revises: 4d29503c6a71
Create Date: 2023-04-23 11:29:28.923975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7842b8dc7f08'
down_revision = '4d29503c6a71'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
